// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAqdDG8mNPDEDlK5yPCquBJhkZJ-B814',
    appId: '1:467666186963:web:bb8bc6014f2ea34432da26',
    messagingSenderId: '467666186963',
    projectId: 'erent-8244f',
    authDomain: 'erent-8244f.firebaseapp.com',
    storageBucket: 'erent-8244f.appspot.com',
    measurementId: 'G-TYT9DZX0ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJ7jX1jrqcwDT9XcDf7sfTAZptjWg29Y',
    appId: '1:467666186963:android:0a0bd34ba9eb97e432da26',
    messagingSenderId: '467666186963',
    projectId: 'erent-8244f',
    storageBucket: 'erent-8244f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvk2IsBY5G_oSiBt3hn-_cC3jYayzDOXY',
    appId: '1:467666186963:ios:388b413459ce620132da26',
    messagingSenderId: '467666186963',
    projectId: 'erent-8244f',
    storageBucket: 'erent-8244f.appspot.com',
    iosClientId:
        '467666186963-ncae1jb4c1f25ocvnpfq5kghsc9q580o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvk2IsBY5G_oSiBt3hn-_cC3jYayzDOXY',
    appId: '1:467666186963:ios:388b413459ce620132da26',
    messagingSenderId: '467666186963',
    projectId: 'erent-8244f',
    storageBucket: 'erent-8244f.appspot.com',
    iosClientId:
        '467666186963-ncae1jb4c1f25ocvnpfq5kghsc9q580o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
